<?php if ($this->messages): ?>
 <div class="flashMessages"><ul>
   <li><?php echo implode('</li><li>', $this->messages) ?></li>
 </ul></div>
<?php endif; ?>
<?php echo $this->orderForm ?>
<?php //echo $this->filterForm ?>
<?php echo $this->paginationControl($this->paginator, 'Sliding', '_table_navigation.phtml');

$columns = array(
    '_bug_description'=>'Bug description',
    '_product_name'   =>'Product name',
    //'bug_id 	'    =>'bug_id 	',
    //'product_id'     =>'product_id by',
);

if ($this->hideBug) {  unset($columns['_bug_description']);  }
if ($this->hideProduct) {  unset($columns['_product_name']);  }

echo Crud_View_Helpers_Paginator::paginatorToTable(
    $this->data,
    $this,
    $columns,
    array(), //options
    $this->model
);
echo $this->paginationControl($this->paginator, 'Sliding', '_table_navigation.phtml');
?>
<a href="<?php echo $this->url(array('action'=>'add'));?>" class="addlink"><?php echo $this->translate('Add a new record') ?></a>